#### default: "body": null
GET http://192.168.5.200:8080/?x=1

#### default: "body": "qwe"
GET http://192.168.5.200:8080/?x=1

qwe

#### default: "body": { "qwe": 1.5 }
GET http://192.168.5.200:8080/a/b/c?x=1&x=2&x=3&q=qwe

{"qwe":1.5}

#### default
GET http://localhost:8080

#### remapped 1
GET http://localhost:8081

#### remapped 2
GET http://localhost:8082

####
GET http://localhost:8080/hello/Jim

####
GET http://localhost:8080/abracadabra
